##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.controlplane:v1.0.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/git-repository/*
COPY ./ /conteco/git-repository/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT="bash" \
    CONTECO_PREENTRYPOINT="/conteco/bin/controlplane/internal/entrypoint"
WORKDIR /conteco/pwd
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="controlplane" \
    CONTECO_NAME="base" \
    CONTECO_TAG="v1.0.2" \
    CONTECO_BASE="external.controlplane:v1.0.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="controlplane" \
      io.vcweb.name="base" \
      io.vcweb.tag="v1.0.2" \
      io.vcweb.base="external.controlplane:v1.0.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="Conteco controlplane base" \
      io.vcweb.description="The Conteco controlplane base image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.controlplane.base --help" 
##### END image.base/Dockerfile/env-labels-footer #####
