#!/usr/bin/env bash
echo "
IMAGE REPO INFO
---------------
label               ${CONTECO_LABEL}
description         ${CONTECO_DESCRIPTION}
realm               ${CONTECO_REALM_RUNTIME}
ecosystem           ${CONTECO_ECOSYSTEM_RUNTIME}
image-type          ${CONTECO_TYPE}
instance-name       ${CONTECO_NAME}
image-tag           ${CONTECO_TAG}
base-image          ${CONTECO_BASE}
image-build         ${CONTECO_BUILD}
"
